# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b6ffbe97a4f95e774bc03f0ce13edeeac93e276273242f47ec057226a6c012c70851f34b80d834adbddd909987422f275c4a56b38a0c9b3fd84e5e612433903

test:
  secret_key_base: 82106ccd05e2439dce684c2737cce25bcdb2e8b78f8d20b48bd7b7de90a9f41ec5f037cd0639d0125c53d1a73a2eeae14fca4a8b7a4e8303d5f9ccd6087be756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
